### ISSUE TITLE
MVImgNet for multi-view classification

### ISSUE THREAD

**Issue by MissingJoe** [GAP-LAB-CUHK-SZ/MVImgNet#11]
Hi, thanks for the fantastic work for multi-view dataset. I'm working on multi-view classification now, so I'm interested in the raw image and image label only. The full dataset is so huge to download. Could you please release the dataset with raw image and label only later?

**Comment by Larry-u** [comment]
Hi, thanks for your interest. 

We feel sorry that currently we don't have plan to release the images-only dataset, because the currently released data contains only raw images and sparse reconstruction results from COLMAP, in which the raw images dominate the disk usage (about 2.x TB). 

So, we don't have enough cloud storage to host a images-only dataset at present, but we are trying to figure out a way to fit every user's demand.
